# 47장 에러 처리

## 47.1 에러 처리의 필요성

우리는 코딩을 하면서 많은 에러를 만나고, 에러가 제로인 프로그램이란 존재하지 않는다. 에러에 대처하지 않았을 때 프로그램은 오류를 범하거나 강제종료된다.

흔히 만나는 에러 중 하나는 `null` 이슈다. JS에서는 `null`에 대한 대처 방안으로 **단축 평가**나 **옵셔널 체이닝 연산자**를 제공하지만 미처 대비하지 못했다면 후에 에러로 이어질 가능성이 크다.

에러를 피하는 것은 불가능하기 때문에 우리는 에러를 예측하고 대비해야 한다.

## 47.2 try ... catch ... finally 문

예외 상황을 피하는 것에는 `if` 구문으로 체크하는 방법도 있지만 `try ... catch ... finally` 구문을 쓰는 방법도 있다. 이를 에러 핸들링이라고 한다.

```js
try {
} catch (err) {
  // try 블록에서 에러가 발생하면 그 Error 객체를 err에 전달한다.
  // err 자리의 변수명은 뭐든 상관없다.
} finally {
  // 에러 유무와 상관 없이 실행
}
```

## 47.3 Error 객체

생성자 함수를 호출하며 인수에 에러 메시지를 넣을 수 있다.

```js
const error = new Error("invalid");
```

인수로 전달한 문자열은 객체의 `message` 프로퍼티에 저장된다. 객체에 존재하는 `stack` 프로퍼티의 값은 에러를 발생시킨 콜스택의 호출 정보를 나타내는 문자열이다.

`Error` 생성자 함수를 포함해 7가지의 에러 객체를 생성하는 함수를 제공한다. 프로토타입은 모두 `Error.prototype`을 상속받는다.

| 생성자 함수    | 인스턴스                                                                           |
| -------------- | ---------------------------------------------------------------------------------- |
| Error          | 일반적 에러 객체                                                                   |
| SyntaxError    | 자바스크립트 문법에 맞지 않는 문을 해석할 때 발생하는 에러 객체                    |
| ReferenceError | 참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체                             |
| TypeError      | 피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체             |
| RangeError     | 숫자값의 허용 범위를 벗어났을 때 발생하는 에러 객체                                |
| URIError       | `encodeURI` 또는 `decodeURI` 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체 |
| EvalError      | `eval` 함수에서 발생하는 에러 객체                                                 |

## 47.4 throw 문

에러 객체를 만드는 것만으로는 에러가 발생하지 않는다. 에러 발생을 위해선 `try` 블록에서 `throw` 문으로 에러 객체를 던져야 한다.

```js
try {
  throw new Error("wrong");
} catch (error) {
  console.log(error);
}
```

던져진 에러객체는 `catch` 로 전달되고 `catch` 코드 블록이 실행된다.
